import Head from "next/head";
import { Header, Footer } from '@/components/elements'
import React, { ReactNode } from 'react';

type LayoutProps = {
  children: ReactNode;
  metaTitle?: string;
  metaDescription?: string;
};

export const Layout: React.FC<LayoutProps> = ({ children, metaTitle, metaDescription }) => {
  return (
    <div>
      <Head>
        <title>{`Create Next App - ${metaTitle}`}</title>
        <meta
          name="description"
          content={metaDescription || "Generated by create next app"}
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
      <Footer />
    </div>
  );
};